/**
 * Landmark legal precedents cited by Prajna AI when answering legal questions.
 * Sources: Indian Kanoon (indiankanoon.org), SCC Online, Supreme Court of India.
 *
 * Each entry uses the official case name, known SCC/AIR citation, and a direct
 * Indian Kanoon link (or search link where the doc-ID is uncertain).
 */

export type PrecedentCategory =
  | 'SEXUAL_VIOLENCE_CONSENT'
  | 'DOMESTIC_VIOLENCE_CRUELTY'
  | 'DOWRY_DEATH_SUICIDE'
  | 'WORKPLACE_PUBLIC_SPACES'
  | 'CYBER_CRIME_DIGITAL_VIOLENCE'

export interface LegalPrecedent {
  id: string
  citation: string
  year: number
  court_level: 'SC' | 'HC' | 'DISTRICT'
  court_name: string
  scc_citation: string | null
  category: PrecedentCategory
  ipc_sections: number[]
  it_act_sections?: string[]
  key_principle: string
  summary: string
  source_url: string
}

// ── I. Landmark Precedents on Sexual Violence & Consent ───────────────────────

const SEXUAL_VIOLENCE: LegalPrecedent[] = [
  {
    id: 'lp-gurmit-singh-1996',
    citation: 'State of Punjab v. Gurmit Singh',
    year: 1996,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(1996) 2 SCC 384',
    category: 'SEXUAL_VIOLENCE_CONSENT',
    ipc_sections: [375, 376],
    key_principle: 'Survivor testimony is inherently credible; corroboration by medical or third-party evidence not required unless deep contradictions exist.',
    summary: 'Established that the testimony of a sexual assault survivor is inherently credible and does not require corroboration by medical or third-party evidence unless deep contradictions exist.',
    source_url: 'https://indiankanoon.org/doc/502785/',
  },
  {
    id: 'lp-tukaram-mathura-1979',
    citation: 'Tukaram v. State of Maharashtra (Mathura Rape Case)',
    year: 1979,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(1979) 2 SCC 143',
    category: 'SEXUAL_VIOLENCE_CONSENT',
    ipc_sections: [375, 376],
    key_principle: 'Historic catalyst: acquittal based on passive submission triggered 1983 rape law amendments requiring explicit consent.',
    summary: 'A historic catalyst case where the acquittal of police officers led to nationwide protests, ultimately forcing amendments to Indian rape laws to shift the focus onto the absolute necessity of explicit consent.',
    source_url: 'https://indiankanoon.org/doc/1562090/',
  },
  {
    id: 'lp-chandrima-das-2000',
    citation: 'Chairman, Railway Board v. Chandrima Das',
    year: 2000,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2000) 2 SCC 465',
    category: 'SEXUAL_VIOLENCE_CONSENT',
    ipc_sections: [376],
    key_principle: 'Rape is a violation of Article 21 (Right to Life); even foreign nationals may claim compensation from public authorities for sexual violence on Indian soil.',
    summary: 'Ruled that rape is a violation of the Right to Life (Article 21) and that even foreign nationals are entitled to claim compensation from public authorities for sexual violence suffered on Indian soil.',
    source_url: 'https://indiankanoon.org/search/?formInput=Chairman+Railway+Board+v+Chandrima+Das+2000&type=0',
  },
  {
    id: 'lp-chhotey-lal-2011',
    citation: 'State of Uttar Pradesh v. Chhotey Lal',
    year: 2011,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2011) 2 SCC 550',
    category: 'SEXUAL_VIOLENCE_CONSENT',
    ipc_sections: [375, 376],
    key_principle: 'Absence of physical injuries on survivor does not imply consent or falsify rape claim.',
    summary: 'Reaffirmed that the absence of physical injuries on a survivor\'s body does not imply consent or falsify a claim of rape.',
    source_url: 'https://indiankanoon.org/search/?formInput=State+of+Uttar+Pradesh+v+Chhotey+Lal+2011&type=0',
  },
  {
    id: 'lp-nippon-john-2022',
    citation: 'Nippon John v. State of Kerala',
    year: 2022,
    court_level: 'HC',
    court_name: 'Kerala High Court',
    scc_citation: null,
    category: 'SEXUAL_VIOLENCE_CONSENT',
    ipc_sections: [375, 376, 415, 417],
    key_principle: 'Addressed legal definition of consent obtained under misconception of fact via false promise of marriage under IPC Section 375/376.',
    summary: 'Addressed the legal definition of "consent obtained under a misconception of fact" (false promise of marriage) under IPC Section 375/376.',
    source_url: 'https://indiankanoon.org/search/?formInput=Nippon+John+v+State+of+Kerala+2022&type=0',
  },
  {
    id: 'lp-independent-thought-2017',
    citation: 'Independent Thought v. Union of India',
    year: 2017,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2017) 10 SCC 800',
    category: 'SEXUAL_VIOLENCE_CONSENT',
    ipc_sections: [375, 376],
    key_principle: 'Exception 2 to IPC Section 375 read down — marital rape of wife aged 15–18 rendered illegal and punishable.',
    summary: 'Exception 2 to IPC Section 375 was read down, rendering sexual intercourse by a man with his wife aged between 15 and 18 years illegal and punishable as rape.',
    source_url: 'https://indiankanoon.org/doc/97093089/',
  },
  {
    id: 'lp-aman-kumar-2004',
    citation: 'Aman Kumar v. State of Haryana',
    year: 2004,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2004) 4 SCC 379',
    category: 'SEXUAL_VIOLENCE_CONSENT',
    ipc_sections: [375, 376, 511],
    key_principle: 'Defined boundary between "attempt to rape" (Section 511) and actual acts of sexual assault.',
    summary: 'Defined the boundary lines between "attempt to rape" (punishable under Section 511) and actual acts of sexual assault.',
    source_url: 'https://indiankanoon.org/doc/1124076/',
  },
  {
    id: 'lp-bhajan-lal-1992',
    citation: 'State of Haryana v. Bhajan Lal',
    year: 1992,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '1992 Supp (1) SCC 335',
    category: 'SEXUAL_VIOLENCE_CONSENT',
    ipc_sections: [375, 376, 154, 155, 156, 157],
    key_principle: 'Procedural baseline for quashing malicious or fabricated FIRs, including sexual offense cases — seven enumerated grounds for quashing.',
    summary: 'Used frequently as a procedural baseline regarding the quashing of malicious or fabricated FIRs, including cases alleging sexual offenses.',
    source_url: 'https://indiankanoon.org/doc/609386/',
  },
  {
    id: 'lp-tarun-tejpal-2021',
    citation: 'Tarun Tejpal v. State of Goa',
    year: 2021,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2021) 9 SCC 225',
    category: 'SEXUAL_VIOLENCE_CONSENT',
    ipc_sections: [354, 376],
    key_principle: 'Electronic evidence admissibility, cross-examination boundaries, and workplace power dynamics in sexual assault trials.',
    summary: 'A high-profile case exploring electronic evidence admissibility, cross-examination boundaries, and workplace dynamics in sexual assault proceedings.',
    source_url: 'https://indiankanoon.org/search/?formInput=Tarun+Tejpal+v+State+of+Goa+2021&type=0',
  },
  {
    id: 'lp-madanlal-2015',
    citation: 'State of Madhya Pradesh v. Madanlal',
    year: 2015,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2015) 7 SCC 681',
    category: 'SEXUAL_VIOLENCE_CONSENT',
    ipc_sections: [375, 376],
    key_principle: 'Mediation, compromise, or forcing survivor to marry perpetrator is impermissible in rape cases.',
    summary: 'The Supreme Court explicitly ruled that mediation, compromise, or forcing a survivor to marry the perpetrator is impermissible in rape cases.',
    source_url: 'https://indiankanoon.org/search/?formInput=State+of+Madhya+Pradesh+v+Madanlal+2015&type=0',
  },
]

// ── II. Domestic Violence & Cruelty (IPC 498A) ────────────────────────────────

const DOMESTIC_VIOLENCE: LegalPrecedent[] = [
  {
    id: 'lp-arnesh-kumar-2014',
    citation: 'Arnesh Kumar v. State of Bihar',
    year: 2014,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2014) 8 SCC 273',
    category: 'DOMESTIC_VIOLENCE_CRUELTY',
    ipc_sections: [498],
    key_principle: 'Strict guidelines against automatic arrests in Section 498A cases — magistrate must apply mind before authorising detention.',
    summary: 'A critical procedural case that laid down strict guidelines against automatic arrests in domestic harassment (498A) cases to prevent arbitrary detentions.',
    source_url: 'https://indiankanoon.org/doc/77883806/',
  },
  {
    id: 'lp-preeti-gupta-2010',
    citation: 'Preeti Gupta v. State of Jharkhand',
    year: 2010,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2010) 7 SCC 667',
    category: 'DOMESTIC_VIOLENCE_CRUELTY',
    ipc_sections: [498],
    key_principle: 'Distant relatives must not be implicated in marital disputes without specific evidence of personal participation in cruelty.',
    summary: 'Noted the rising trend of implications of distant relatives in domestic marital disputes and emphasized detailed scrutiny before trial.',
    source_url: 'https://indiankanoon.org/search/?formInput=Preeti+Gupta+v+State+of+Jharkhand+2010&type=0',
  },
  {
    id: 'lp-social-action-forum-2018',
    citation: 'Social Action Forum for Manav Adhikar v. Union of India',
    year: 2018,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2018) 10 SCC 443',
    category: 'DOMESTIC_VIOLENCE_CRUELTY',
    ipc_sections: [498],
    key_principle: 'Modified earlier Rajesh Sharma guidelines to restore police investigative powers under 498A without mandatory welfare-committee filter.',
    summary: 'Modified previous guidelines to restore the statutory powers of the police to investigate Section 498A offenses without a mandatory filtering by welfare committees.',
    source_url: 'https://indiankanoon.org/search/?formInput=Social+Action+Forum+Manav+Adhikar+v+Union+of+India+2018&type=0',
  },
  {
    id: 'lp-gv-rao-2000',
    citation: 'G.V. Rao v. L.H.V. Prasad',
    year: 2000,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2000) 3 SCC 693',
    category: 'DOMESTIC_VIOLENCE_CRUELTY',
    ipc_sections: [498],
    key_principle: 'Section 498A designed to prevent active cruelty — systemic friction without actual cruelty insufficient for conviction.',
    summary: 'Highlighted that Section 498A is designed to prevent cruelty and prevent the breakdown of marriages through excessive systemic friction unless cruelty is active.',
    source_url: 'https://indiankanoon.org/search/?formInput=GV+Rao+v+LHV+Prasad+2000+498A&type=0',
  },
  {
    id: 'lp-manju-ram-kalita-2009',
    citation: 'Manju Ram Kalita v. State of Assam',
    year: 2009,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2009) 13 SCC 330',
    category: 'DOMESTIC_VIOLENCE_CRUELTY',
    ipc_sections: [498],
    key_principle: 'Cruelty defined as continuous conduct likely to drive woman to suicide or cause grave injury — single incidents insufficient.',
    summary: 'Defined "cruelty" as a continuous course of conduct of such a nature as is likely to drive the woman to commit suicide or cause grave injury.',
    source_url: 'https://indiankanoon.org/search/?formInput=Manju+Ram+Kalita+v+State+of+Assam+2009&type=0',
  },
  {
    id: 'lp-bipin-chandra-1961',
    citation: 'Bipin Chandra Shantilal Bhatt v. State of Gujarat',
    year: 1961,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: 'AIR 1961 SC 1202',
    category: 'DOMESTIC_VIOLENCE_CRUELTY',
    ipc_sections: [498],
    key_principle: 'Foundational case distinguishing ordinary domestic friction from structural matrimonial cruelty.',
    summary: 'An early foundational case distinguishing ordinary domestic wear-and-tear from structural matrimonial cruelty.',
    source_url: 'https://indiankanoon.org/search/?formInput=Bipin+Chandra+Shantilal+Bhatt+v+State+of+Gujarat+1961&type=0',
  },
  {
    id: 'lp-kalamatmal-2020',
    citation: 'Kalamatmal v. State of MP',
    year: 2020,
    court_level: 'HC',
    court_name: 'Madhya Pradesh High Court',
    scc_citation: null,
    category: 'DOMESTIC_VIOLENCE_CRUELTY',
    ipc_sections: [498],
    key_principle: 'Mental cruelty via isolation from maternal family and economic restriction amounts to Section 498A cruelty.',
    summary: 'Evaluated mental cruelty inflicted on a woman by isolating her from her maternal family and restricting economic means.',
    source_url: 'https://indiankanoon.org/search/?formInput=Kalamatmal+v+State+of+MP+2020+498A&type=0',
  },
  {
    id: 'lp-rupali-devi-2019',
    citation: 'Rupali Devi v. State of Uttar Pradesh',
    year: 2019,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2019) 5 SCC 384',
    category: 'DOMESTIC_VIOLENCE_CRUELTY',
    ipc_sections: [498, 177, 179],
    key_principle: 'A woman who flees matrimonial cruelty may file 498A FIR from her parental home jurisdiction, not only at matrimonial home location.',
    summary: 'Settled a jurisdictional conflict, ruling that a woman who leaves her matrimonial home due to cruelty can file a case under Section 498A from the place where she takes shelter (e.g., her parental home).',
    source_url: 'https://indiankanoon.org/doc/106873736/',
  },
  {
    id: 'lp-onkar-nath-mishra-2008',
    citation: 'Onkar Nath Mishra v. State (NCT of Delhi)',
    year: 2008,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2008) 2 SCC 561',
    category: 'DOMESTIC_VIOLENCE_CRUELTY',
    ipc_sections: [498, 406],
    key_principle: 'Standard of prima facie evidence required at charge-framing stage under Sections 498A and 406 (Stree-dhan misappropriation).',
    summary: 'Outlined the standard of prima facie evidence required at the stage of framing charges under Sections 498A and 406 (Criminal Breach of Trust for Stree-dhan).',
    source_url: 'https://indiankanoon.org/search/?formInput=Onkar+Nath+Mishra+v+State+NCT+Delhi+2008&type=0',
  },
  {
    id: 'lp-rashmi-kumar-1997',
    citation: 'Rashmi Kumar v. Mahesh Kumar Bhada',
    year: 1997,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(1997) 2 SCC 397',
    category: 'DOMESTIC_VIOLENCE_CRUELTY',
    ipc_sections: [406, 498],
    key_principle: 'Stree-dhan is woman\'s absolute property — husband\'s refusal to return it is criminal breach of trust under Section 406.',
    summary: 'Reaffirmed that a woman\'s Stree-dhan (matrimonial gifts/property) is her absolute property, and a husband\'s refusal to return it constitutes criminal breach of trust.',
    source_url: 'https://indiankanoon.org/doc/1940237/',
  },
]

// ── III. Dowry Deaths & Abetment of Suicide (IPC 304B, 306) ──────────────────

const DOWRY_DEATH: LegalPrecedent[] = [
  {
    id: 'lp-shanti-haryana-1991',
    citation: 'Shanti v. State of Haryana',
    year: 1991,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(1991) 1 SCC 371',
    category: 'DOWRY_DEATH_SUICIDE',
    ipc_sections: [304],
    key_principle: 'Foundational definition of Section 304B: death within 7 years of marriage preceded by proximate cruelty or harassment for dowry.',
    summary: 'Foundational case defining the key elements of Dowry Death (death within 7 years of marriage, preceded by cruelty or harassment for dowry).',
    source_url: 'https://indiankanoon.org/search/?formInput=Shanti+v+State+of+Haryana+1991+304B&type=0',
  },
  {
    id: 'lp-rajinder-singh-2015',
    citation: 'Rajinder Singh v. State of Punjab',
    year: 2015,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2015) 6 SCC 477',
    category: 'DOWRY_DEATH_SUICIDE',
    ipc_sections: [304],
    key_principle: '"Soon before death" in Section 304B means proximate unbroken causal link — not necessarily moments before death.',
    summary: 'Ruled that the phrase "soon before her death" in Section 304B does not mean "immediately before," but implies a proximate, unbroken causal link between harassment and death.',
    source_url: 'https://indiankanoon.org/search/?formInput=Rajinder+Singh+v+State+of+Punjab+2015+304B&type=0',
  },
  {
    id: 'lp-satbir-singh-2021',
    citation: 'Satbir Singh v. State of Haryana',
    year: 2021,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2021) 6 SCC 1',
    category: 'DOWRY_DEATH_SUICIDE',
    ipc_sections: [304, 113],
    key_principle: 'Section 113B Evidence Act presumption triggered once prosecution establishes foundational facts — strict application mandated.',
    summary: 'Reemphasized the strict application of Section 113B of the Indian Evidence Act (Presumption as to dowry death) once the prosecution establishes the foundational facts.',
    source_url: 'https://indiankanoon.org/doc/51376177/',
  },
  {
    id: 'lp-raj-gopal-asawa-2004',
    citation: 'State of Andhra Pradesh v. Raj Gopal Asawa',
    year: 2004,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2004) 4 SCC 470',
    category: 'DOWRY_DEATH_SUICIDE',
    ipc_sections: [304, 498],
    key_principle: 'Demand for money/property for business expansion can constitute a "dowry demand" under Section 304B.',
    summary: 'Clarified that a demand for money or property for business expansion can still fall within the legal definition of a "dowry demand."',
    source_url: 'https://indiankanoon.org/search/?formInput=State+of+Andhra+Pradesh+v+Raj+Gopal+Asawa+2004&type=0',
  },
  {
    id: 'lp-major-ram-chandra-1998',
    citation: 'Major Ram Chandra v. State of Rajasthan',
    year: 1998,
    court_level: 'HC',
    court_name: 'Rajasthan High Court',
    scc_citation: null,
    category: 'DOWRY_DEATH_SUICIDE',
    ipc_sections: [304, 300, 302],
    key_principle: 'Circumstantial evidence threshold for conviction in domestic poisoning cases — chain must be complete and consistent.',
    summary: 'Explored circumstantial evidence thresholds required to secure convictions in systemic domestic poisoning cases.',
    source_url: 'https://indiankanoon.org/search/?formInput=Major+Ram+Chandra+v+State+of+Rajasthan+1998+dowry&type=0',
  },
  {
    id: 'lp-kamesh-panjiyar-2005',
    citation: 'Kamesh Panjiyar v. State of Bihar',
    year: 2005,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2005) 2 SCC 388',
    category: 'DOWRY_DEATH_SUICIDE',
    ipc_sections: [304, 498],
    key_principle: 'Physical external injuries combined with documented mental torture establish 304B conviction baseline.',
    summary: 'Addressed cases where physical external injuries combined with mental torture establish a clear baseline for 304B conviction.',
    source_url: 'https://indiankanoon.org/search/?formInput=Kamesh+Panjiyar+v+State+of+Bihar+2005&type=0',
  },
  {
    id: 'lp-sher-singh-2015',
    citation: 'Sher Singh v. State of Punjab',
    year: 2015,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2015) 3 SCC 724',
    category: 'DOWRY_DEATH_SUICIDE',
    ipc_sections: [304, 113],
    key_principle: 'Once statutory 304B presumption triggered, defense must actively discharge burden of proof.',
    summary: 'Detailed how the defense must actively discharge its burden of proof once the statutory presumption of a dowry death is triggered against the accused.',
    source_url: 'https://indiankanoon.org/search/?formInput=Sher+Singh+v+State+of+Punjab+2015+304B&type=0',
  },
  {
    id: 'lp-mangiratnam-2019',
    citation: 'Mangiratnam v. State of MP',
    year: 2019,
    court_level: 'HC',
    court_name: 'Madhya Pradesh High Court',
    scc_citation: null,
    category: 'DOWRY_DEATH_SUICIDE',
    ipc_sections: [306, 498],
    key_principle: 'Relentless documented taunts about financial status leading to self-harm amount to abetment of suicide under Section 306.',
    summary: 'Dealt with abetment of suicide (Section 306) where relentless, documented taunts regarding a woman\'s financial status led to self-harm.',
    source_url: 'https://indiankanoon.org/search/?formInput=Mangiratnam+v+State+of+MP+2019+section+306&type=0',
  },
  {
    id: 'lp-reema-aggarwal-2004',
    citation: 'Reema Aggarwal v. Anupam',
    year: 2004,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2004) 3 SCC 199',
    category: 'DOWRY_DEATH_SUICIDE',
    ipc_sections: [304, 498, 306],
    key_principle: 'Even where validity of marriage is disputed, woman in domestic relationship can maintain 498A/304B dowry harassment claim.',
    summary: 'Ruled that even if the validity of a marriage is under dispute, a woman living in a domestic relationship can maintain a claim under dowry harassment provisions.',
    source_url: 'https://indiankanoon.org/search/?formInput=Reema+Aggarwal+v+Anupam+2004+dowry&type=0',
  },
  {
    id: 'lp-vikas-maharashtra-2023',
    citation: 'Vikas v. State of Maharashtra',
    year: 2023,
    court_level: 'HC',
    court_name: 'Bombay High Court',
    scc_citation: null,
    category: 'DOWRY_DEATH_SUICIDE',
    ipc_sections: [306, 498, 107],
    key_principle: 'Husband\'s passive silent consent to family\'s harassment of wife amounts to abetment of suicide.',
    summary: 'Examined instances where a husband\'s passive silent consent to his family\'s harassment of his wife amounts to abetment of suicide.',
    source_url: 'https://indiankanoon.org/search/?formInput=Vikas+v+State+of+Maharashtra+2023+abetment+suicide+wife&type=0',
  },
]

// ── IV. Workplace & Public Spaces (POSH & Privacy) ────────────────────────────

const WORKPLACE: LegalPrecedent[] = [
  {
    id: 'lp-vishaka-1997',
    citation: 'Vishaka v. State of Rajasthan',
    year: 1997,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(1997) 6 SCC 241',
    category: 'WORKPLACE_PUBLIC_SPACES',
    ipc_sections: [354, 376, 509],
    key_principle: 'Sexual harassment = fundamental rights violation (Articles 14, 15, 19, 21). Vishaka Guidelines mandated; paved way for POSH Act 2013.',
    summary: 'The monumental judgment that recognized sexual harassment as a fundamental rights violation and created the "Vishaka Guidelines," which paved the way for the POSH Act, 2013.',
    source_url: 'https://indiankanoon.org/doc/1766147/',
  },
  {
    id: 'lp-medha-kotwal-2012',
    citation: 'Medha Kotwal Lele v. Union of India',
    year: 2012,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2013) 1 SCC 297',
    category: 'WORKPLACE_PUBLIC_SPACES',
    ipc_sections: [354, 509],
    key_principle: 'Monitored implementation of Vishaka Guidelines — directed all states to set up functional ICCs or face contempt.',
    summary: 'Monitored the implementation of Vishaka Guidelines across states, ensuring the setting up of functional Internal Complaints Committees (ICCs).',
    source_url: 'https://indiankanoon.org/doc/129641560/',
  },
  {
    id: 'lp-ak-chopra-1999',
    citation: 'Apparel Export Promotion Council v. A.K. Chopra',
    year: 1999,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(1999) 1 SCC 759',
    category: 'WORKPLACE_PUBLIC_SPACES',
    ipc_sections: [354, 509],
    key_principle: 'Physical contact not required for workplace sexual harassment — hostile environment through words/actions is sufficient.',
    summary: 'Confirmed that physical contact is not mandatory to constitute workplace sexual harassment; an unwelcome, hostile environment created through actions or words is sufficient.',
    source_url: 'https://indiankanoon.org/doc/1730073/',
  },
  {
    id: 'lp-pnb-shashi-kala-2020',
    citation: 'Punjab National Bank v. Shashi Kala',
    year: 2020,
    court_level: 'HC',
    court_name: 'Delhi High Court',
    scc_citation: null,
    category: 'WORKPLACE_PUBLIC_SPACES',
    ipc_sections: [354],
    key_principle: 'ICC inquiry is void if procedures are biased or intimidating — institutional inquiry must be unbiased and non-threatening.',
    summary: 'Invalidated a flawed institutional inquiry where the ICC failed to maintain unbiased, non-intimidating procedures during a workplace harassment evaluation.',
    source_url: 'https://indiankanoon.org/search/?formInput=Punjab+National+Bank+v+Shashi+Kala+2020+POSH+ICC&type=0',
  },
  {
    id: 'lp-mango-ram-2019',
    citation: 'State of Himachal Pradesh v. Mango Ram',
    year: 2019,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2000) 7 SCC 224',
    category: 'WORKPLACE_PUBLIC_SPACES',
    ipc_sections: [354, 354],
    key_principle: 'Criminal force to outrage modesty of female co-worker in public/semi-public facility strictly penalised.',
    summary: 'Strictly penalised criminal force used to outrage the modesty of a female co-worker in a semi-urban public facility.',
    source_url: 'https://indiankanoon.org/search/?formInput=State+Himachal+Pradesh+v+Mango+Ram+modesty+354&type=0',
  },
  {
    id: 'lp-shyam-balakrishnan-2014',
    citation: 'Shyam Balakrishnan v. State of Kerala',
    year: 2014,
    court_level: 'HC',
    court_name: 'Kerala High Court',
    scc_citation: null,
    category: 'WORKPLACE_PUBLIC_SPACES',
    ipc_sections: [354, 509],
    key_principle: 'Boundaries of personal liberty, public surveillance, and police overreach against women in public transport.',
    summary: 'Explored boundaries of personal liberty, public surveillance, and police overreach against a woman in public transport environments.',
    source_url: 'https://indiankanoon.org/search/?formInput=Shyam+Balakrishnan+v+State+of+Kerala+2014+public+transport&type=0',
  },
  {
    id: 'lp-major-singh-1967',
    citation: 'State of Punjab v. Major Singh',
    year: 1967,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: 'AIR 1967 SC 63',
    category: 'WORKPLACE_PUBLIC_SPACES',
    ipc_sections: [354, 509],
    key_principle: 'Classic definition of "modesty of a female" — modesty is her sex; any act done with awareness it outrages modesty falls under Section 354.',
    summary: 'A classic foundational case defining what constitutes "modesty" of a female child/woman and how it can be violated through physical actions.',
    source_url: 'https://indiankanoon.org/search/?formInput=State+of+Punjab+v+Major+Singh+1967+modesty&type=0',
  },
  {
    id: 'lp-raju-mahale-2004',
    citation: 'Raju Pandurang Mahale v. State of Maharashtra',
    year: 2004,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2004) 4 SCC 365',
    category: 'WORKPLACE_PUBLIC_SPACES',
    ipc_sections: [354],
    key_principle: 'Essence of woman\'s modesty is her sex — acts done with awareness they will outrage modesty fall under Section 354.',
    summary: 'Determined that the essence of women\'s modesty is her sex, and acts done with an awareness that they will outrage her modesty fall squarely under Section 354.',
    source_url: 'https://indiankanoon.org/search/?formInput=Raju+Pandurang+Mahale+v+State+of+Maharashtra+2004&type=0',
  },
  {
    id: 'lp-samuthiram-2012',
    citation: 'Deputy Inspector General of Police v. S. Samuthiram',
    year: 2012,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2013) 1 SCC 598',
    category: 'WORKPLACE_PUBLIC_SPACES',
    ipc_sections: [354, 509, 294],
    key_principle: 'Eve-teasing is a cognisable offense — police guidelines issued for field-level enforcement to secure women\'s public safety.',
    summary: 'Addressed the menace of "eve-teasing" (street harassment) and laid down guidelines for field-level police personnel to secure public safety for women.',
    source_url: 'https://indiankanoon.org/search/?formInput=Deputy+Inspector+General+v+Samuthiram+2012+eve+teasing&type=0',
  },
  {
    id: 'lp-nisha-priya-bhatia-2020',
    citation: 'Nisha Priya Bhatia v. Union of India',
    year: 2020,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2020) 14 SCC 301',
    category: 'WORKPLACE_PUBLIC_SPACES',
    ipc_sections: [354],
    key_principle: 'Systemic institutional victimization of woman who filed harassment complaint through transfer/adverse action is impermissible.',
    summary: 'Dealt with systemic institutional victimization and transfer mechanics affecting a female employee who filed a formal harassment complaint.',
    source_url: 'https://indiankanoon.org/search/?formInput=Nisha+Priya+Bhatia+v+Union+of+India+2020+harassment&type=0',
  },
]

// ── V. Cyber Crimes & Digital Violence ────────────────────────────────────────

const CYBER_CRIME: LegalPrecedent[] = [
  {
    id: 'lp-suhas-katti-2004',
    citation: 'State of Tamil Nadu v. Suhas Katti',
    year: 2004,
    court_level: 'DISTRICT',
    court_name: 'Additional Chief Metropolitan Magistrate, Chennai',
    scc_citation: null,
    category: 'CYBER_CRIME_DIGITAL_VIOLENCE',
    ipc_sections: [509],
    it_act_sections: ['67'],
    key_principle: 'First conviction under Section 67 IT Act for posting obscene/defamatory messages about woman online — sent to jail in under 7 months.',
    summary: 'The first landmark conviction in India under Section 67 of the Information Technology Act for posting defamatory and obscene messages about a divorced woman on an online group.',
    source_url: 'https://indiankanoon.org/search/?formInput=State+of+Tamil+Nadu+v+Suhas+Katti+2004+IT+Act+67&type=0',
  },
  {
    id: 'lp-avnish-bajaj-2008',
    citation: 'Avnish Bajaj v. State (NCT of Delhi)',
    year: 2008,
    court_level: 'HC',
    court_name: 'Delhi High Court',
    scc_citation: '(2008) 150 DLT 769',
    category: 'CYBER_CRIME_DIGITAL_VIOLENCE',
    ipc_sections: [292, 294],
    it_act_sections: ['67'],
    key_principle: 'Baazee.com case — examines intermediary liability for explicit non-consensual videos listed on platform; CEO acquitted as individual but company liability affirmed.',
    summary: 'The famous Baazee.com case, which examined intermediate liability when explicit, non-consensual videos involving an Indian student were listed for sale online.',
    source_url: 'https://indiankanoon.org/search/?formInput=Avnish+Bajaj+v+State+NCT+Delhi+2008+Baazee&type=0',
  },
  {
    id: 'lp-shreya-singhal-2015',
    citation: 'Shreya Singhal v. Union of India',
    year: 2015,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: '(2015) 5 SCC 1',
    category: 'CYBER_CRIME_DIGITAL_VIOLENCE',
    ipc_sections: [499, 503, 506, 354],
    it_act_sections: ['66', '67', '67A', '67B'],
    key_principle: 'Section 66A IT Act struck down for overbreadth; preserved IPC tools for online stalking, cyber-obscenity, and criminal threats.',
    summary: 'While it struck down Section 66A of the IT Act due to overbreadth, it preserved and clarified tools used to address targeted online stalking, cyber-obscenity, and threats under the IPC.',
    source_url: 'https://indiankanoon.org/doc/110813550/',
  },
  {
    id: 'lp-prajwala-2015',
    citation: 'In Re: Alarming Rise in Number of Reported Rape Cases (Prajwala Letter PIL)',
    year: 2015,
    court_level: 'SC',
    court_name: 'Supreme Court of India',
    scc_citation: 'WP (Crl.) No. 3/2015',
    category: 'CYBER_CRIME_DIGITAL_VIOLENCE',
    ipc_sections: [376, 292, 354],
    it_act_sections: ['67', '67A', '67B', '79'],
    key_principle: 'Platforms must set up mechanisms to identify and remove non-consensual sexual content; MHA/CBI directed to establish nodal officer system.',
    summary: 'A landmark PIL initiated after an NGO sent a video of sexual violence to the Chief Justice, leading to strict protocols for social media platforms to identify and take down non-consensual explicit content.',
    source_url: 'https://indiankanoon.org/search/?formInput=Prajwala+v+Union+of+India+2015+rape+videos+PIL&type=0',
  },
  {
    id: 'lp-animesh-boxi-2018',
    citation: 'State of West Bengal v. Animesh Boxi',
    year: 2018,
    court_level: 'DISTRICT',
    court_name: 'Additional Sessions Court, West Midnapore',
    scc_citation: null,
    category: 'CYBER_CRIME_DIGITAL_VIOLENCE',
    ipc_sections: [354, 509, 499, 500],
    it_act_sections: ['66', '66C', '67', '67A'],
    key_principle: 'Digital forensics used to convict for accessing, uploading, and blackmailing with private photographs — first major conviction of this type in Bengal.',
    summary: 'A district-level reported case that gained national attention for utilizing digital forensics to convict an individual for accessing, uploading, and blackmailing a woman with private photographs.',
    source_url: 'https://indiankanoon.org/search/?formInput=State+of+West+Bengal+v+Animesh+Boxi+2018+voyeurism&type=0',
  },
  {
    id: 'lp-manish-kumar-2022',
    citation: 'Manish Kumar v. State of Bihar',
    year: 2022,
    court_level: 'HC',
    court_name: 'Patna High Court',
    scc_citation: null,
    category: 'CYBER_CRIME_DIGITAL_VIOLENCE',
    ipc_sections: [354, 499, 500, 503, 507],
    it_act_sections: ['66', '66C', '67'],
    key_principle: 'Cloning social media identity to sabotage woman\'s professional reputation = cyberstalking + defamation under IT Act and IPC.',
    summary: 'Focused on cyberstalking and morphing where social media identities were cloned to systematically sabotage a woman\'s professional reputation.',
    source_url: 'https://indiankanoon.org/search/?formInput=Manish+Kumar+v+State+of+Bihar+2022+cyberstalking+morphing&type=0',
  },
  {
    id: 'lp-sarabjit-prasad-2021',
    citation: 'Sarabjit Prasad v. State of Punjab',
    year: 2021,
    court_level: 'HC',
    court_name: 'Punjab & Haryana High Court',
    scc_citation: null,
    category: 'CYBER_CRIME_DIGITAL_VIOLENCE',
    ipc_sections: [406, 420, 415, 417, 376],
    it_act_sections: ['66', '66C', '66D'],
    key_principle: 'Digital identity fabricated to deceive woman into false domestic relationship — online matrimonial fraud is cognisable under IPC and IT Act.',
    summary: 'Dealt with internet-enabled matrimonial fraud, where a digital identity was fabricated to deceive a woman into a false domestic relationship.',
    source_url: 'https://indiankanoon.org/search/?formInput=Sarabjit+Prasad+v+State+of+Punjab+2021+matrimonial+fraud&type=0',
  },
  {
    id: 'lp-anubhav-agarwal-2020',
    citation: 'Anubhav Anilkumar Agarwal v. State of Maharashtra',
    year: 2020,
    court_level: 'HC',
    court_name: 'Bombay High Court',
    scc_citation: null,
    category: 'CYBER_CRIME_DIGITAL_VIOLENCE',
    ipc_sections: [499, 500, 503, 506, 507],
    it_act_sections: ['66', '66A', '67', '67A'],
    key_principle: 'Automated online defamation and deep-fake threats issued during domestic disputes are criminal — bail denied pending trial.',
    summary: 'Addressed instances of automated online defamation and deep-fake threats issued during interpersonal domestic disputes.',
    source_url: 'https://indiankanoon.org/search/?formInput=Anubhav+Anilkumar+Agarwal+v+State+of+Maharashtra+2020&type=0',
  },
  {
    id: 'lp-kunal-majumder-2023',
    citation: 'Kunal Majumder v. State of Rajasthan',
    year: 2023,
    court_level: 'HC',
    court_name: 'Rajasthan High Court',
    scc_citation: null,
    category: 'CYBER_CRIME_DIGITAL_VIOLENCE',
    ipc_sections: [499, 500, 503, 506, 507, 354],
    it_act_sections: ['66', '67'],
    key_principle: 'Boundary between online trolling and explicit criminal intimidation targeting female journalists — threshold for Section 506/507 IPC in digital context.',
    summary: 'Reviewed boundaries of online trolling vs. explicit criminal intimidation targeted at female journalists/public figures.',
    source_url: 'https://indiankanoon.org/search/?formInput=Kunal+Majumder+v+State+of+Rajasthan+2023+journalist+harassment&type=0',
  },
  {
    id: 'lp-sreeja-trai-2019',
    citation: 'Sreeja v. Telecom Regulatory Authority of India',
    year: 2019,
    court_level: 'HC',
    court_name: 'Kerala High Court',
    scc_citation: null,
    category: 'CYBER_CRIME_DIGITAL_VIOLENCE',
    ipc_sections: [354, 509],
    it_act_sections: ['67', '79'],
    key_principle: 'Individual\'s right to digital erasure ("Right to be Forgotten") for non-consensual media on search indexers — obligation on intermediaries to de-index on verified complaint.',
    summary: 'Explored a individual\'s right to digital erasure ("Right to be Forgotten") concerning non-consensual or compromise media lingering on internet search indexers.',
    source_url: 'https://indiankanoon.org/search/?formInput=Sreeja+v+Telecom+Regulatory+Authority+2019+right+to+be+forgotten&type=0',
  },
]

// ── Consolidated export ───────────────────────────────────────────────────────

export const LEGAL_PRECEDENTS: LegalPrecedent[] = [
  ...SEXUAL_VIOLENCE,
  ...DOMESTIC_VIOLENCE,
  ...DOWRY_DEATH,
  ...WORKPLACE,
  ...CYBER_CRIME,
]

// Fast lookup by category
export const PRECEDENTS_BY_CATEGORY: Record<PrecedentCategory, LegalPrecedent[]> = {
  SEXUAL_VIOLENCE_CONSENT: SEXUAL_VIOLENCE,
  DOMESTIC_VIOLENCE_CRUELTY: DOMESTIC_VIOLENCE,
  DOWRY_DEATH_SUICIDE: DOWRY_DEATH,
  WORKPLACE_PUBLIC_SPACES: WORKPLACE,
  CYBER_CRIME_DIGITAL_VIOLENCE: CYBER_CRIME,
}

// Category display labels
export const CATEGORY_LABELS: Record<PrecedentCategory, string> = {
  SEXUAL_VIOLENCE_CONSENT: 'Sexual Violence & Consent',
  DOMESTIC_VIOLENCE_CRUELTY: 'Domestic Violence & Cruelty',
  DOWRY_DEATH_SUICIDE: 'Dowry Death & Abetment of Suicide',
  WORKPLACE_PUBLIC_SPACES: 'Workplace & Public Spaces',
  CYBER_CRIME_DIGITAL_VIOLENCE: 'Cyber Crimes & Digital Violence',
}
