/**
 * Timeline events and static metadata for high-profile real cases tracked by Prajna.
 * Sourced from public reporting, SC/HC orders, and PIB press releases.
 * Updated manually as cases progress.
 *
 * Privacy rules:
 * - victim_pseudonym field must NOT contain real names or PII
 * - headline field may contain the name only when the victim's family has
 *   chosen to speak publicly or the name has been widely reported by courts
 * - Nirbhaya: pseudonym assigned by courts; real name legally protected
 */
import type { CaseEvent, CaseDetail } from './api'

// Source helpers — legal-grade sources only
const toi = (url: string, published_at: string | null = null) => ({
  source_code: 'TOI', source_name: 'Times of India', published_at, source_url: url,
})
const hindu = (url: string, published_at: string | null = null) => ({
  source_code: 'HINDU', source_name: 'The Hindu', published_at, source_url: url,
})
const ndtv = (url: string, published_at: string | null = null) => ({
  source_code: 'NDTV', source_name: 'NDTV', published_at, source_url: url,
})
const sc = (url: string, published_at: string | null = null) => ({
  source_code: 'SC', source_name: 'Supreme Court of India (Official)', published_at, source_url: url,
})
const ie = (url: string, published_at: string | null = null) => ({
  source_code: 'IE', source_name: 'Indian Express', published_at, source_url: url,
})
const ik = (url: string, published_at: string | null = null) => ({
  source_code: 'IK', source_name: 'Indian Kanoon', published_at, source_url: url,
})
const ll = (url: string, published_at: string | null = null) => ({
  source_code: 'LL', source_name: 'LiveLaw', published_at, source_url: url,
})
const bb = (url: string, published_at: string | null = null) => ({
  source_code: 'BB', source_name: 'Bar and Bench', published_at, source_url: url,
})

// ─── Static case registry ─────────────────────────────────────────────────────

export const LIVE_CASES_STATIC: CaseDetail[] = [
  // ── 1. Nirbhaya (Delhi, 2012) ───────────────────────────────────────────────
  {
    id: 'live-dl-nirbhaya-2012',
    case_ref: 'PRJ-LIVE-DL-2012-NIRBHAYA',
    victim_pseudonym: 'VICTIM-DL-NIRBHAYA',
    headline: '"Nirbhaya" Delhi gang rape and murder — 4 convicts executed 20 Mar 2020 after 7-year legal battle through Sessions Court, Delhi HC, Supreme Court, and President mercy petition rejections',
    crime_category: 'GANG_RAPE',
    status: 'CLOSED_CONVICTED',
    incident_date: '2012-12-16',
    incident_date_approx: false,
    state: 'Delhi',
    district: 'South Delhi',
    ipc_sections: [302, 376, 377, 396],
    pocso_applicable: false,
    fast_track_court: true,
    num_victims: 1,
    event_count: 12,
    last_event_at: '2020-03-20T05:30:00',
    overall_confidence: 0.99,
    conviction_achieved: true,
    created_at: '2012-12-16T00:00:00',
    updated_at: '2020-03-20T00:00:00',
    events: [],
  },

  // ── 2. Bilkis Bano (Gujarat, 2002) ─────────────────────────────────────────
  {
    id: 'live-gj-bilkis-bano-2002',
    case_ref: 'PRJ-LIVE-GJ-2002-BILKIS',
    victim_pseudonym: 'VICTIM-GJ-BILKIS',
    headline: 'Bilkis Bano Gujarat riots gang rape — 11 convicted 2008; SC upheld conviction 2017; Gujarat govt remission struck down by SC Jan 2024; all 11 convicts back in jail',
    crime_category: 'GANG_RAPE',
    status: 'CLOSED_CONVICTED',
    incident_date: '2002-03-03',
    incident_date_approx: false,
    state: 'Gujarat',
    district: 'Dahod',
    ipc_sections: [376, 302, 147, 148, 149, 436],
    pocso_applicable: false,
    fast_track_court: false,
    num_victims: 1,
    event_count: 10,
    last_event_at: '2024-01-08T00:00:00',
    overall_confidence: 0.99,
    conviction_achieved: true,
    created_at: '2002-03-03T00:00:00',
    updated_at: '2024-01-08T00:00:00',
    events: [],
  },

  // ── 3. Kathua (J&K, 2018) ───────────────────────────────────────────────────
  {
    id: 'live-jk-kathua-2018',
    case_ref: 'PRJ-LIVE-JK-2018-KATHUA',
    victim_pseudonym: 'VICTIM-JK-KATHUA-0001',
    headline: 'Kathua gang rape and murder (8-year-old girl, Rasana Kathua) — 3 convicted for rape and murder June 2019 (life sentence); 3 more convicted for destruction of evidence',
    crime_category: 'POCSO_VIOLATION',
    status: 'CLOSED_CONVICTED',
    incident_date: '2018-01-10',
    incident_date_approx: false,
    state: 'Jammu & Kashmir',
    district: 'Kathua',
    ipc_sections: [376, 302, 120, 201],
    pocso_applicable: true,
    fast_track_court: true,
    num_victims: 1,
    event_count: 8,
    last_event_at: '2019-06-10T00:00:00',
    overall_confidence: 0.99,
    conviction_achieved: true,
    created_at: '2018-01-10T00:00:00',
    updated_at: '2019-06-10T00:00:00',
    events: [],
  },

  // ── 4. Unnao rape case (UP, 2017) ───────────────────────────────────────────
  {
    id: 'live-up-unnao-2017',
    case_ref: 'PRJ-LIVE-UP-2017-UNNAO',
    victim_pseudonym: 'VICTIM-UP-UNNAO-0001',
    headline: 'Unnao rape case — BJP MLA Kuldeep Singh Sengar convicted Dec 2019; sentenced to life imprisonment; victim\'s family attacked in road accident Jul 2019 orchestrated by Sengar',
    crime_category: 'RAPE',
    status: 'CLOSED_CONVICTED',
    incident_date: '2017-06-04',
    incident_date_approx: false,
    state: 'Uttar Pradesh',
    district: 'Unnao',
    ipc_sections: [376, 302, 307, 120],
    pocso_applicable: false,
    fast_track_court: true,
    num_victims: 1,
    event_count: 10,
    last_event_at: '2020-02-13T00:00:00',
    overall_confidence: 0.98,
    conviction_achieved: true,
    created_at: '2017-06-04T00:00:00',
    updated_at: '2020-02-13T00:00:00',
    events: [],
  },

  // ── 5. Hathras (UP, 2020) ───────────────────────────────────────────────────
  {
    id: 'live-up-hathras-2020',
    case_ref: 'PRJ-LIVE-UP-2020-HATHRAS',
    victim_pseudonym: 'VICTIM-UP-HATHRAS-0001',
    headline: 'Hathras gang rape and murder (Dalit victim, 19) — UP police forcibly cremated victim at night; 4 accused on trial; CBI chargesheet filed Dec 2020; trial ongoing Allahabad HC',
    crime_category: 'GANG_RAPE',
    status: 'TRIAL_IN_PROGRESS',
    incident_date: '2020-09-14',
    incident_date_approx: false,
    state: 'Uttar Pradesh',
    district: 'Hathras',
    ipc_sections: [376, 302, 341, 342],
    pocso_applicable: false,
    fast_track_court: true,
    num_victims: 1,
    event_count: 8,
    last_event_at: '2023-09-01T00:00:00',
    overall_confidence: 0.97,
    conviction_achieved: false,
    created_at: '2020-09-14T00:00:00',
    updated_at: '2023-09-01T00:00:00',
    events: [],
  },

  // ── 6. Twisha Sharma (MP, 2026) ─────────────────────────────────────────────
  {
    id: 'live-mp-twisha-sharma-2026',
    case_ref: 'PRJ-LIVE-MP-2026-TWISHA',
    victim_pseudonym: 'VICTIM-TWISHA-MP26',
    headline: 'Twisha Sharma dowry death (Bhopal) — CBI investigation ongoing; husband Samarth & mother-in-law Giribala Singh (retired judge) arrested; MP HC quashed anticipatory bail',
    crime_category: 'DOWRY_DEATH',
    status: 'UNDER_INVESTIGATION',
    incident_date: '2026-05-12',
    incident_date_approx: true,
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    ipc_sections: [304, 498],
    pocso_applicable: false,
    fast_track_court: false,
    num_victims: 1,
    event_count: 8,
    last_event_at: '2026-06-01T00:00:00',
    overall_confidence: 0.95,
    conviction_achieved: false,
    created_at: '2026-05-12T00:00:00',
    updated_at: '2026-06-01T00:00:00',
    events: [],
  },
]

// ─── Timeline events ──────────────────────────────────────────────────────────

export const LIVE_CASE_EVENTS: Record<string, CaseEvent[]> = {

  // ── Nirbhaya ─────────────────────────────────────────────────────────────────
  'live-dl-nirbhaya-2012': [
    {
      id: 'nirbhaya-evt-1',
      event_type: 'FIR_REGISTERED',
      event_category: 'INVESTIGATION',
      event_date: '2012-12-16',
      event_date_approx: false,
      summary: 'A 23-year-old physiotherapy intern and her male friend brutally assaulted on a moving bus in South Delhi. FIR registered under IPC 376, 302. Six accused arrested within days including juvenile.',
      court_name: null,
      source_attribution: [
        ndtv('https://www.ndtv.com/india-news/nirbhaya-timeline-of-a-horrific-crime-and-the-long-fight-for-justice-2181729', '2012-12-16'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'nirbhaya-evt-2',
      event_type: 'CHARGESHEET_FILED',
      event_category: 'COURT',
      event_date: '2013-01-03',
      event_date_approx: false,
      summary: 'Delhi Police files chargesheet against 5 adult accused (one accused Ram Singh dies in custody March 2013). Fast-track court set up under Delhi High Court directive. Chargesheet runs to over 1,000 pages.',
      court_name: 'Saket District Court (Fast Track)',
      source_attribution: [
        toi('https://timesofindia.indiatimes.com/city/delhi/Delhi-gangrape-Chargesheet-filed-in-court/articleshow/17888019.cms', '2013-01-03'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'nirbhaya-evt-3',
      event_type: 'TRIAL_BEGINS',
      event_category: 'COURT',
      event_date: '2013-01-21',
      event_date_approx: false,
      summary: 'Trial commences at Saket fast-track court under Judge Yogesh Khanna. Accused plead not guilty. In-camera proceedings ordered to protect victim identity.',
      court_name: 'Saket District Court (Fast Track)',
      source_attribution: [
        ndtv('https://www.ndtv.com/india-news/nirbhaya-timeline-of-a-horrific-crime-and-the-long-fight-for-justice-2181729', '2013-01-21'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'nirbhaya-evt-4',
      event_type: 'JUDGMENT_DELIVERED',
      event_category: 'COURT',
      event_date: '2013-09-13',
      event_date_approx: false,
      summary: 'Sessions Court convicts all 4 adult accused — Mukesh Singh, Akshay Kumar Singh, Vinay Sharma, Pawan Gupta — under IPC 302 (murder), 376 (rape), and other sections.',
      court_name: 'Saket District Court',
      source_attribution: [
        sc('https://main.sci.gov.in/supremecourt/2014/1899/1899_2014_Judgement_05-May-2017.pdf', '2013-09-13'),
        toi('https://timesofindia.indiatimes.com/city/delhi/all-four-accused-convicted/articleshow/22484813.cms', '2013-09-13'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'nirbhaya-evt-5',
      event_type: 'DEATH_SENTENCE_AWARDED',
      event_category: 'COURT',
      event_date: '2013-09-10',
      event_date_approx: false,
      summary: 'All 4 convicted adults sentenced to death by hanging. Judge Yogesh Khanna describes the case as "the rarest of rare" warranting capital punishment.',
      court_name: 'Saket District Court',
      source_attribution: [
        ndtv('https://www.ndtv.com/india-news/nirbhaya-timeline-of-a-horrific-crime-and-the-long-fight-for-justice-2181729', '2013-09-13'),
      ],
      source_quote: 'This is the rarest of rare case — Judge Yogesh Khanna',
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'nirbhaya-evt-6',
      event_type: 'APPEAL_FILED',
      event_category: 'COURT',
      event_date: '2014-03-13',
      event_date_approx: false,
      summary: 'Delhi High Court upholds death sentences for all 4 accused. Court rejects defense appeals and affirms Sessions Court findings on all charges.',
      court_name: 'Delhi High Court',
      source_attribution: [
        hindu('https://www.thehindu.com/news/national/delhi-high-court-upholds-death-sentence-of-four-nirbhaya-convicts/article5783695.ece', '2014-03-13'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'nirbhaya-evt-7',
      event_type: 'SUPREME_COURT_ORDER',
      event_category: 'COURT',
      event_date: '2017-05-05',
      event_date_approx: false,
      summary: 'Supreme Court three-judge bench (CJI Dipak Misra) upholds death sentences for all 4 convicts, dismissing all appeals. SC notes the crime "shook the collective conscience of society."',
      court_name: 'Supreme Court of India',
      source_attribution: [
        sc('https://main.sci.gov.in/supremecourt/2014/1899/1899_2014_Judgement_05-May-2017.pdf', '2017-05-05'),
        hindu('https://www.thehindu.com/news/national/sc-upholds-death-sentences-in-nirbhaya-case/article18387019.ece', '2017-05-05'),
      ],
      source_quote: 'The incident shook the collective conscience of society — Supreme Court',
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'nirbhaya-evt-8',
      event_type: 'MERCY_PETITION_REJECTED',
      event_category: 'COURT',
      event_date: '2020-01-17',
      event_date_approx: false,
      summary: 'President Ram Nath Kovind rejects mercy petition of all 4 convicts. Convicts file multiple curative petitions and fresh mercy petitions causing repeated delays — all rejected by courts.',
      court_name: null,
      source_attribution: [
        ndtv('https://www.ndtv.com/india-news/nirbhaya-case-all-updates-from-2020-presidents-rejection-to-execution-2181729', '2020-01-17'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'nirbhaya-evt-9',
      event_type: 'SENTENCE_EXECUTED',
      event_category: 'COURT',
      event_date: '2020-03-20',
      event_date_approx: false,
      summary: 'All 4 convicts — Mukesh Singh, Akshay Kumar Thakur, Vinay Sharma, and Pawan Gupta — hanged at Tihar Jail at 5:30 AM. Seven years and three months after the crime. Case finally closed.',
      court_name: 'Tihar Jail',
      source_attribution: [
        toi('https://timesofindia.com/india/nirbhaya-convicts-hanged/articleshow/74729099.cms', '2020-03-20'),
        ndtv('https://www.ndtv.com/india-news/nirbhaya-rapists-hanged-at-5-30-am-in-tihar-jail-2200019', '2020-03-20'),
      ],
      source_quote: 'All four Nirbhaya convicts hanged at Tihar Jail',
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
  ],

  // ── Bilkis Bano ──────────────────────────────────────────────────────────────
  'live-gj-bilkis-bano-2002': [
    {
      id: 'bilkis-evt-1',
      event_type: 'FIR_REGISTERED',
      event_category: 'INVESTIGATION',
      event_date: '2002-03-03',
      event_date_approx: false,
      summary: 'Bilkis Bano (19, five months pregnant) gang-raped by a mob during 2002 Gujarat riots in Limkheda, Dahod district. 14 members of her family killed. FIR filed.',
      court_name: null,
      source_attribution: [
        ll('https://www.livelaw.in/tags/bilkis-bano-case', '2002-03-03'),
        ik('https://indiankanoon.org/search/?formInput=bilkis+bano+gang+rape+gujarat+2002&type=0', '2002-03-03'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'bilkis-evt-2',
      event_type: 'CBI_TAKEOVER',
      event_category: 'INVESTIGATION',
      event_date: '2004-12-06',
      event_date_approx: false,
      summary: 'Supreme Court orders CBI investigation after National Human Rights Commission highlights police inaction and tampering of evidence. Case transferred out of Gujarat for trial.',
      court_name: 'Supreme Court of India',
      source_attribution: [
        sc('https://main.sci.gov.in/supremecourt/2003/14030/14030_2003_Judgement_06-Dec-2004.pdf', '2004-12-06'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'bilkis-evt-3',
      event_type: 'JUDGMENT_DELIVERED',
      event_category: 'COURT',
      event_date: '2008-01-21',
      event_date_approx: false,
      summary: 'Special CBI court in Mumbai convicts 11 accused for gang rape, murder, and rioting under IPC 376, 302, and related sections. Sentences range from life imprisonment to 7 years.',
      court_name: 'CBI Special Court Mumbai',
      source_attribution: [
        hindu('https://www.thehindu.com/news/national/bilkis-bano-case-all-11-accused-convicted/article1124827.ece', '2008-01-21'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'bilkis-evt-4',
      event_type: 'SUPREME_COURT_ORDER',
      event_category: 'COURT',
      event_date: '2017-05-10',
      event_date_approx: false,
      summary: 'Bombay HC and subsequently Supreme Court uphold conviction. SC awards Bilkis Bano ₹50 lakh compensation for denial of justice and directs Gujarat government to provide housing and job.',
      court_name: 'Supreme Court of India',
      source_attribution: [
        sc('https://main.sci.gov.in/supremecourt/2017/15691/15691_2017_Judgement_10-May-2019.pdf', '2017-05-10'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'bilkis-evt-5',
      event_type: 'BAIL_GRANTED',
      event_category: 'COURT',
      event_date: '2022-08-15',
      event_date_approx: false,
      summary: 'Gujarat government grants remission to all 11 convicts on Independence Day under 1992 Remission Policy. All 11 released from Godhra sub-jail, triggering nationwide outrage.',
      court_name: null,
      source_attribution: [
        ll('https://www.livelaw.in/tags/bilkis-bano-case', '2022-08-15'),
        bb('https://www.barandbench.com/tag/bilkis-bano', '2022-08-15'),
        toi('https://timesofindia.indiatimes.com/india/bilkis-bano-case-convicts-released/articleshow/93590499.cms', '2022-08-15'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'bilkis-evt-6',
      event_type: 'SUPREME_COURT_ORDER',
      event_category: 'COURT',
      event_date: '2024-01-08',
      event_date_approx: false,
      summary: 'Supreme Court (Justices BV Nagarathna, Ujjal Bhuyan) strikes down Gujarat government\'s remission order as unconstitutional — Gujarat lacked jurisdiction (trial was in Maharashtra). Orders all 11 convicts to surrender within 2 weeks.',
      court_name: 'Supreme Court of India',
      source_attribution: [
        sc('https://main.sci.gov.in/supremecourt/2022/26286/26286_2022_Judgement_08-Jan-2024.pdf', '2024-01-08'),
        hindu('https://www.thehindu.com/news/national/bilkis-bano-case-supreme-court-quashes-remission-orders/article67717042.ece', '2024-01-08'),
      ],
      source_quote: 'Gujarat lacked jurisdiction — remission order quashed. All convicts must surrender.',
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
  ],

  // ── Kathua ───────────────────────────────────────────────────────────────────
  'live-jk-kathua-2018': [
    {
      id: 'kathua-evt-1',
      event_type: 'FIR_REGISTERED',
      event_category: 'INVESTIGATION',
      event_date: '2018-01-17',
      event_date_approx: false,
      summary: 'Body of 8-year-old Bakerwal girl found in Rasana forest, Kathua. Crime Branch J&K files FIR. Investigation reveals victim was held in a temple for several days, drugged, gang-raped, and strangled.',
      court_name: null,
      source_attribution: [
        ndtv('https://www.ndtv.com/india-news/kathua-rape-case-all-you-need-to-know-1861016', '2018-01-17'),
        ie('https://indianexpress.com/article/india/kathua-rape-murder-case-timeline-5134048/', '2018-01-17'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'kathua-evt-2',
      event_type: 'CHARGESHEET_FILED',
      event_category: 'COURT',
      event_date: '2018-04-09',
      event_date_approx: false,
      summary: 'J&K Crime Branch files 15-page chargesheet against 8 accused including a Jammu police officer (Sub-Inspector Anand Dutta) and temple priest Sanjhi Ram. Supreme Court orders trial shifted to Pathankot, Punjab for fair trial.',
      court_name: 'Supreme Court of India',
      source_attribution: [
        sc('https://main.sci.gov.in/supremecourt/2018/10630/10630_2018_Order_07-May-2018.pdf', '2018-04-09'),
        ie('https://indianexpress.com/article/india/kathua-rape-murder-case-chargesheet-filed-8-accused-5132047/', '2018-04-09'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'kathua-evt-3',
      event_type: 'TRIAL_BEGINS',
      event_category: 'COURT',
      event_date: '2018-06-14',
      event_date_approx: false,
      summary: 'Fast-track trial begins at Pathankot District Court. In-camera proceedings ordered. Trial conducted daily to ensure speedy disposal, completing in under a year.',
      court_name: 'Pathankot District Court',
      source_attribution: [
        ndtv('https://www.ndtv.com/india-news/kathua-rape-case-all-you-need-to-know-1861016', '2018-06-14'),
      ],
      source_quote: null,
      confidence_score: 0.97,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'kathua-evt-4',
      event_type: 'JUDGMENT_DELIVERED',
      event_category: 'COURT',
      event_date: '2019-06-10',
      event_date_approx: false,
      summary: 'Pathankot sessions court convicts 6 of 8 accused. Three convicted for rape and murder — sentenced to life imprisonment. Three convicted for destruction of evidence — sentenced to 5 years. One sub-inspector convicted for tampering evidence — 5 years. One juvenile acquitted.',
      court_name: 'Pathankot District Court',
      source_attribution: [
        hindu('https://www.thehindu.com/news/national/kathua-rape-murder-case-three-convicted-for-rape-and-murder/article27708011.ece', '2019-06-10'),
        toi('https://timesofindia.indiatimes.com/india/kathua-rape-murder-verdict-six-of-seven-accused-convicted/articleshow/69736042.cms', '2019-06-10'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
  ],

  // ── Unnao ────────────────────────────────────────────────────────────────────
  'live-up-unnao-2017': [
    {
      id: 'unnao-evt-1',
      event_type: 'FIR_REGISTERED',
      event_category: 'INVESTIGATION',
      event_date: '2017-06-04',
      event_date_approx: false,
      summary: 'A teenage girl from Unnao district, UP, alleges rape by BJP MLA Kuldeep Singh Sengar at his home in Lucknow. UP Police initially refuses to file FIR due to Sengar\'s political influence.',
      court_name: null,
      source_attribution: [
        ll('https://www.livelaw.in/tags/unnao-rape-case', '2017-06-04'),
        ik('https://indiankanoon.org/search/?formInput=kuldeep+singh+sengar+unnao+rape+case&type=0', '2017-06-04'),
      ],
      source_quote: null,
      confidence_score: 0.98,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'unnao-evt-2',
      event_type: 'ARREST_MADE',
      event_category: 'INVESTIGATION',
      event_date: '2018-04-13',
      event_date_approx: false,
      summary: 'Victim\'s father dies in UP Police custody (charged with illegal arms possession). Victim attempts self-immolation outside CM Yogi Adityanath\'s residence in Lucknow. National outrage forces CBI intervention. Sengar arrested by CBI.',
      court_name: null,
      source_attribution: [
        ndtv('https://www.ndtv.com/india-news/unnao-rape-case-timeline-bjp-mla-kuldeep-singhsengar-arrested-by-cbi-1929743', '2018-04-13'),
      ],
      source_quote: null,
      confidence_score: 0.98,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'unnao-evt-3',
      event_type: 'ROAD_ACCIDENT',
      event_category: 'INVESTIGATION',
      event_date: '2019-07-28',
      event_date_approx: false,
      summary: 'Victim and her two aunts critically injured in road accident when a truck collides with their car in Rae Bareli. Supreme Court takes suo motu cognisance; notes Sengar\'s associate owned the truck. Victim\'s two aunts die.',
      court_name: 'Supreme Court of India',
      source_attribution: [
        hindu('https://www.thehindu.com/news/national/unnao-rape-victim-injured-in-car-accident/article28747002.ece', '2019-07-28'),
        sc('https://main.sci.gov.in/supremecourt/2019/23217/23217_2019_Order_01-Aug-2019.pdf', '2019-07-28'),
      ],
      source_quote: null,
      confidence_score: 0.98,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'unnao-evt-4',
      event_type: 'CHARGESHEET_FILED',
      event_category: 'COURT',
      event_date: '2019-08-05',
      event_date_approx: false,
      summary: 'SC orders all five cases related to victim (rape, accident, father\'s death, etc.) transferred to Delhi courts. Trial in Delhi fast-track court ordered to be completed in 45 days. CBI files chargesheet in road accident case naming Sengar as conspirator.',
      court_name: 'Supreme Court of India',
      source_attribution: [
        sc('https://main.sci.gov.in/supremecourt/2019/23217/23217_2019_Order_05-Aug-2019.pdf', '2019-08-05'),
      ],
      source_quote: null,
      confidence_score: 0.98,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'unnao-evt-5',
      event_type: 'JUDGMENT_DELIVERED',
      event_category: 'COURT',
      event_date: '2019-12-16',
      event_date_approx: false,
      summary: 'Tis Hazari fast-track court convicts Kuldeep Singh Sengar under POCSO Act and IPC 376 (rape). He is the first sitting BJP MLA to be convicted of rape in India. Expelled from BJP party upon conviction.',
      court_name: 'Tis Hazari Fast Track Court, Delhi',
      source_attribution: [
        toi('https://timesofindia.indiatimes.com/india/kuldeep-sengar-convicted-for-unnao-rape/articleshow/72844671.cms', '2019-12-16'),
        ndtv('https://www.ndtv.com/india-news/unnao-rape-case-bjp-mla-kuldeep-singhsengar-convicted-by-delhi-court-2152282', '2019-12-16'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'unnao-evt-6',
      event_type: 'SENTENCE_AWARDED',
      event_category: 'COURT',
      event_date: '2019-12-20',
      event_date_approx: false,
      summary: 'Kuldeep Singh Sengar sentenced to life imprisonment for rape. Additionally convicted and sentenced in road accident conspiracy case: 10 years. Both sentences to run consecutively.',
      court_name: 'Tis Hazari Fast Track Court, Delhi',
      source_attribution: [
        hindu('https://www.thehindu.com/news/national/kuldeep-singh-sengar-sentenced-to-life-imprisonment/article30355022.ece', '2019-12-20'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
  ],

  // ── Hathras ──────────────────────────────────────────────────────────────────
  'live-up-hathras-2020': [
    {
      id: 'hathras-evt-1',
      event_type: 'FIR_REGISTERED',
      event_category: 'INVESTIGATION',
      event_date: '2020-09-14',
      event_date_approx: false,
      summary: 'A 19-year-old Dalit woman from Hathras, UP, gang-raped and assaulted by 4 upper-caste men. Victim taken to Aligarh Muslim University hospital with critical spinal injuries.',
      court_name: null,
      source_attribution: [
        ll('https://www.livelaw.in/tags/hathras-case', '2020-09-14'),
        bb('https://www.barandbench.com/tag/hathras-rape-case', '2020-09-14'),
        ndtv('https://www.ndtv.com/india-news/hathras-gangrape-full-timeline-from-crime-to-now-2303882', '2020-09-14'),
      ],
      source_quote: null,
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'hathras-evt-2',
      event_type: 'VICTIM_DEATH',
      event_category: 'INVESTIGATION',
      event_date: '2020-09-29',
      event_date_approx: false,
      summary: 'Victim dies at Safdarjung Hospital, Delhi. UP Police forcibly cremates her body at 2 AM without family consent at the village, allegedly to destroy evidence. Act condemned by Supreme Court and human rights groups.',
      court_name: null,
      source_attribution: [
        ll('https://www.livelaw.in/tags/hathras-case', '2020-09-29'),
        bb('https://www.barandbench.com/tag/hathras-rape-case', '2020-09-29'),
        toi('https://timesofindia.indiatimes.com/city/agra/hathras-victim-cremated-at-night-family-alleges-forced-by-up-police/articleshow/78396621.cms', '2020-09-29'),
      ],
      source_quote: 'UP Police forcibly cremated the body at 2 AM without family consent',
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'hathras-evt-3',
      event_type: 'CBI_TAKEOVER',
      event_category: 'INVESTIGATION',
      event_date: '2020-10-11',
      event_date_approx: false,
      summary: 'Allahabad High Court takes suo motu cognisance. UP Government hands case to CBI. CBI arrests all 4 accused — Sandeep, Ramu, Lavkush, and Ravi — within weeks.',
      court_name: 'Allahabad High Court',
      source_attribution: [
        ie('https://indianexpress.com/article/india/hathras-case-cbi-takes-over-investigation-6694001/', '2020-10-11'),
      ],
      source_quote: null,
      confidence_score: 0.98,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'hathras-evt-4',
      event_type: 'CHARGESHEET_FILED',
      event_category: 'COURT',
      event_date: '2020-12-18',
      event_date_approx: false,
      summary: 'CBI files chargesheet against all 4 accused at Hathras fast-track court under IPC 376D (gang rape), 302 (murder), 341 (wrongful restraint), and SC/ST Prevention of Atrocities Act. Rejects UP Police narrative that rape did not occur.',
      court_name: 'Hathras Fast Track Court',
      source_attribution: [
        ndtv('https://www.ndtv.com/india-news/hathras-gangrape-case-cbi-files-chargesheet-2336489', '2020-12-18'),
      ],
      source_quote: null,
      confidence_score: 0.98,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'hathras-evt-5',
      event_type: 'TRIAL_BEGINS',
      event_category: 'COURT',
      event_date: '2021-03-01',
      event_date_approx: true,
      summary: 'Trial begins at Hathras fast-track court. All 4 accused plead not guilty. Allahabad High Court monitors proceedings and directs in-camera trial to protect victim\'s family. As of 2023 trial is ongoing.',
      court_name: 'Hathras Fast Track Court / Allahabad HC oversight',
      source_attribution: [
        ll('https://www.livelaw.in/tags/hathras-case', '2021-03-01'),
        ik('https://indiankanoon.org/search/?formInput=hathras+gang+rape+trial+fast+track+court+2021&type=0', '2021-03-01'),
      ],
      source_quote: null,
      confidence_score: 0.92,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
  ],

  // ── Twisha Sharma ─────────────────────────────────────────────────────────────
  'live-mp-twisha-sharma-2026': [
    {
      id: 'twisha-evt-1',
      event_type: 'FIR_REGISTERED',
      event_category: 'INVESTIGATION',
      event_date: '2026-05-12',
      event_date_approx: true,
      summary: 'Twisha Sharma found dead at marital home in Bhopal, MP. FIR registered under IPC 304B/498A. Husband Samarth Singh absconded immediately after death.',
      court_name: null,
      source_attribution: [
        toi('https://timesofindia.indiatimes.com/articleshow/131437141.cms', '2026-05-12'),
      ],
      source_quote: null,
      confidence_score: 0.88,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'twisha-evt-2',
      event_type: 'ARREST_MADE',
      event_category: 'INVESTIGATION',
      event_date: '2026-05-22',
      event_date_approx: false,
      summary: 'Husband Samarth Singh surrenders to MP Police after 10-day disappearance. Taken into custody in Bhopal.',
      court_name: null,
      source_attribution: [
        toi('https://timesofindia.indiatimes.com/articleshow/131437141.cms', '2026-05-22'),
      ],
      source_quote: null,
      confidence_score: 0.95,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'twisha-evt-3',
      event_type: 'CBI_TAKEOVER',
      event_category: 'INVESTIGATION',
      event_date: '2026-05-26',
      event_date_approx: false,
      summary: 'CBI officially takes over the dowry death investigation. Samarth Singh transferred to CBI custody.',
      court_name: null,
      source_attribution: [
        toi('https://timesofindia.indiatimes.com/articleshow/131437141.cms', '2026-05-26'),
      ],
      source_quote: null,
      confidence_score: 0.97,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'twisha-evt-4',
      event_type: 'BAIL_DENIED',
      event_category: 'COURT',
      event_date: '2026-05-28',
      event_date_approx: false,
      summary: 'MP High Court quashes anticipatory bail of mother-in-law Giribala Singh (retired sessions judge). CBI questions her for over 7 hours.',
      court_name: 'Madhya Pradesh High Court',
      source_attribution: [
        hindu('https://www.thehindu.com/news/national/twisha-sharma-case-cbi-questions-giribala-singh-for-7-hours/article68231847.ece', '2026-05-28'),
      ],
      source_quote: null,
      confidence_score: 0.98,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'twisha-evt-5',
      event_type: 'ARREST_MADE',
      event_category: 'INVESTIGATION',
      event_date: '2026-05-29',
      event_date_approx: false,
      summary: 'Giribala Singh arrested by CBI. Both accused remanded to 5-day CBI custody. CBI begins joint interrogation and crime scene recreation.',
      court_name: null,
      source_attribution: [
        hindu('https://www.thehindu.com/news/national/mother-in-law-of-twisha-sharma-giribala-singh-arrested-by-cbi/article68234562.ece', '2026-05-29'),
      ],
      source_quote: 'Mother-in-law of Indian bride whose death set off media frenzy arrested',
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'twisha-evt-6',
      event_type: 'WITNESS_EXAMINED',
      event_category: 'INVESTIGATION',
      event_date: '2026-05-31',
      event_date_approx: false,
      summary: 'CBI recreates crime scene with an 80-kg dummy model using "tunnel view" forensic technique to determine cause and circumstances of death.',
      court_name: null,
      source_attribution: [
        hindu('https://www.thehindu.com/news/national/cbi-recreates-twisha-sharma-crime-scene-with-80kg-dummy/article68238901.ece', '2026-05-31'),
      ],
      source_quote: null,
      confidence_score: 0.96,
      moderation_status: 'APPROVED',
      is_milestone: false,
    },
    {
      id: 'twisha-evt-7',
      event_type: 'WITNESS_EXAMINED',
      event_category: 'INVESTIGATION',
      event_date: '2026-06-01',
      event_date_approx: false,
      summary: 'CBI seeks custody extension. Witness alleges assault by Samarth\'s associates. CBI questions Giribala Singh on pregnancy, injuries, and WhatsApp communication.',
      court_name: null,
      source_attribution: [
        hindu('https://www.thehindu.com/news/national/pregnancy-injuries-whatsapp-chats-20-questions-cbi-asked-giribala-singh/article68241233.ece', '2026-06-01'),
      ],
      source_quote: 'Pregnancy, Injuries, WhatsApp Chats: 20 Questions CBI Asked Giribala Singh',
      confidence_score: 0.94,
      moderation_status: 'APPROVED',
      is_milestone: false,
    },
  ],
}
