/**
 * Timeline events for high-profile real cases tracked by Nyaya.
 * Sourced from public reporting; updated manually as cases progress.
 * Keyed by live_cases.id.
 */
import type { CaseEvent } from './api'

const ANI = {
  source_code: 'ANI',
  source_name: 'Asian News International',
  published_at: null,
  source_url: '',
}
const TOI = {
  source_code: 'TOI',
  source_name: 'Times of India',
  published_at: null,
  source_url: 'https://timesofindia.indiatimes.com/articleshow/131437141.cms',
}
const HINDU = {
  source_code: 'HINDU',
  source_name: 'The Hindu',
  published_at: null,
  source_url: '',
}

export const LIVE_CASE_EVENTS: Record<string, CaseEvent[]> = {
  'live-mp-twisha-sharma-2026': [
    {
      id: 'twisha-evt-1',
      event_type: 'FIR_REGISTERED',
      event_category: 'INVESTIGATION',
      event_date: '2026-05-12',
      event_date_approx: true,
      summary: 'Twisha Sharma found dead at marital home in Bhopal, Madhya Pradesh. FIR registered. Husband Samarth Singh absconded immediately after death, hiding in Jabalpur for approximately 10 days.',
      court_name: null,
      source_attribution: [TOI],
      source_quote: null,
      confidence_score: 0.88,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'twisha-evt-2',
      event_type: 'ARREST_MADE',
      event_category: 'INVESTIGATION',
      event_date: '2026-05-22',
      event_date_approx: false,
      summary: 'Husband Samarth Singh surrenders to Madhya Pradesh police after 10-day disappearance. Taken into custody in Bhopal.',
      court_name: null,
      source_attribution: [TOI, ANI],
      source_quote: null,
      confidence_score: 0.95,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'twisha-evt-3',
      event_type: 'MEDICAL_EXAMINATION',
      event_category: 'MEDICAL',
      event_date: '2026-05-23',
      event_date_approx: false,
      summary: 'Medical examination of Samarth Singh conducted in Bhopal. Madhya Pradesh police formally refer the dowry death case to CBI citing high-profile nature and victim\'s family demands.',
      court_name: null,
      source_attribution: [TOI],
      source_quote: null,
      confidence_score: 0.92,
      moderation_status: 'APPROVED',
      is_milestone: false,
    },
    {
      id: 'twisha-evt-4',
      event_type: 'ARREST_MADE',
      event_category: 'INVESTIGATION',
      event_date: '2026-05-26',
      event_date_approx: false,
      summary: 'CBI officially takes over the dowry death investigation. Samarth Singh transferred to CBI custody. Central agency begins independent probe.',
      court_name: null,
      source_attribution: [ANI, TOI],
      source_quote: null,
      confidence_score: 0.97,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'twisha-evt-5',
      event_type: 'BAIL_DENIED',
      event_category: 'COURT',
      event_date: '2026-05-28',
      event_date_approx: false,
      summary: 'Madhya Pradesh High Court quashes anticipatory bail of mother-in-law Giribala Singh (retired sessions judge). CBI questions Giribala Singh for over 7 hours; seeks 5-day custodial remand.',
      court_name: 'Madhya Pradesh High Court',
      source_attribution: [HINDU, TOI],
      source_quote: null,
      confidence_score: 0.98,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'twisha-evt-6',
      event_type: 'ARREST_MADE',
      event_category: 'INVESTIGATION',
      event_date: '2026-05-29',
      event_date_approx: false,
      summary: 'Giribala Singh (mother-in-law, retired judge) arrested by CBI following bail cancellation. Both Samarth Singh and Giribala Singh remanded to 5-day CBI custody until June 2, 2026. CBI plans joint interrogation and crime scene recreation.',
      court_name: null,
      source_attribution: [HINDU, ANI],
      source_quote: 'Mother-in-law of Indian bride whose death set off media frenzy arrested',
      confidence_score: 0.99,
      moderation_status: 'APPROVED',
      is_milestone: true,
    },
    {
      id: 'twisha-evt-7',
      event_type: 'WITNESS_EXAMINED',
      event_category: 'INVESTIGATION',
      event_date: '2026-05-31',
      event_date_approx: false,
      summary: 'CBI recreates crime scene at marital home using an 80-kilogram dummy model. \'Tunnel view\' forensic technique employed to reconstruct Twisha\'s final hours and determine exact cause and circumstances of death.',
      court_name: null,
      source_attribution: [HINDU, ANI],
      source_quote: null,
      confidence_score: 0.96,
      moderation_status: 'APPROVED',
      is_milestone: false,
    },
    {
      id: 'twisha-evt-8',
      event_type: 'WITNESS_EXAMINED',
      event_category: 'INVESTIGATION',
      event_date: '2026-06-01',
      event_date_approx: false,
      summary: 'CBI seeks custody extension for both accused beyond June 2 deadline. Witness alleges assault by husband Samarth\'s associates — investigation widens. CBI questions Giribala Singh on pregnancy, injuries, and WhatsApp communication evidence.',
      court_name: null,
      source_attribution: [ANI, HINDU],
      source_quote: 'Pregnancy, Injuries, WhatsApp Chats: 20 Questions CBI Asked Giribala Singh',
      confidence_score: 0.94,
      moderation_status: 'APPROVED',
      is_milestone: false,
    },
  ],
}
