apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: nyaya-dev

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
    target:
      kind: HorizontalPodAutoscaler

images:
  - name: ghcr.io/nyaya-platform/nyaya-api
    newTag: dev
  - name: ghcr.io/nyaya-platform/nyaya-frontend
    newTag: dev
  - name: ghcr.io/nyaya-platform/nyaya-privacy-engine
    newTag: dev
  - name: ghcr.io/nyaya-platform/nyaya-ai-extractor
    newTag: dev
  - name: ghcr.io/nyaya-platform/nyaya-entity-resolver
    newTag: dev
  - name: ghcr.io/nyaya-platform/nyaya-timeline-engine
    newTag: dev
  - name: ghcr.io/nyaya-platform/nyaya-persistence-worker
    newTag: dev
  - name: ghcr.io/nyaya-platform/nyaya-ingestion
    newTag: dev
